# Generated by Django 2.0.2 on 2018-02-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('calories_from_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=8)),
                ('restaurant', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('macro_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Entree')),
            ],
        ),
    ]
