# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180215_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entree',
            old_name='calorie',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='entree',
            old_name='sugars',
            new_name='sugar',
        ),
    ]
